name: Test

on:
  pull_request:
    branches:
      - dev
      - stg
      - prd
    types:
      - closed

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
      - name: test run
        run: |
          echo ${{ vars.TEST_VAR }}
          echo ${{ github.base_ref }}
